### ISSUE TITLE
Common MDX error documentation updates

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#1123]
**Summary**

- What route inside platform should the common mdx errors page live? Ex: next.carbondesignsystem.com/common-mdx-errors
- What should this page format look like? 
Sample content: https://github.com/carbon-design-system/carbon-platform/blob/e9372e24aa1b0504a0f11bf68e9a37ef7cf6de7d/services/web-app/pages/common-mdx-errors.mdx
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/40550942/183444774-61c7d4fd-376f-496b-bdb3-52d2f4ccf832.png">
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/40550942/183444832-1217eec6-0cac-4d4b-b825-ec2473c4bd7e.png">

**Job stories**

What value will this deliver?

1. When my authored content on platform has an error, I want to get more information on the error, so I can fix it.

**Acceptance criteria**

What requirements must be met to complete this request?

- [ ] determine desired url for page content to live in
  - we want this to live in storybook next to the mdx components themselves so it is "in context"
- [ ] design pattern for a problem/solution (i.e. how should the header/title look? should it start with text or an image? what is the general sentence structure of a solution?) (#1176)

**TODO**

- [ ] Incorporate design updates from #1176 into existing content
- [ ] Move page to (eventually) deployed storybook
  - Q: is this the mdx-components storybook? or the general platform storybook?

**Comment by francinelucca** [comment]
what release should we mark this? is this v1? @mattrosno  @kingtraceyj @aubrey-oneal  👀

**Comment by mattrosno** [comment]
@francinelucca is this for our testing purposes? If so, can this live in Storybook?

Or is this for contributors to help them troubleshoot why their content isn't rendering?

**Comment by francinelucca** [comment]
> @francinelucca is this for our testing purposes? If so, can this live in Storybook?
> 
> Or is this for contributors to help them troubleshoot why their content isn't rendering?

@mattrosno the latter! it's a list with all the common errors that can appear on the remotely loaded content and some guidance on how to fix

**Comment by mattrosno** [comment]
@francinelucca this looks nice in the website and I can see how this could fit in the Contributing section. I'm just thinking about how all MDX documentation to browse available MDX components, to copy/paste code snippets, etc. is in Storybook. Would we want this documentation to live alongside the MDX component docs in Storybook? This entire page of markdown could be a story that live in a "MDX / Troubleshooting" section in Storybook, if we want.

Just throwing out something to consider. @aubrey-oneal

**Comment by mattrosno** [comment]
An example of how docs can live in Storybook is Carbon Charts. It has a top "Docs" section with getting started content. We could have a top Docs section for getting started, but also help content like this, as well.

https://charts.carbondesignsystem.com/?path=/story/docs-getting-started--vanilla

**Comment by kingtraceyj** [comment]
we think this should go in storybook.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1123?planning-poker) with Zenhub @alisonjoseph @francinelucca @jdharvey-ibm

**Comment by mattrosno** [comment]
We'll re-evaluate after @jdharvey-ibm adds tasks.

**Comment by kingtraceyj** [comment]
Here is the Figma for the documentation pattern: https://www.figma.com/file/WyfqQh9R1VXYZErfmsNDVH/Platform_MDXerrors?node-id=317%3A11967

<img width="616" alt="image" src="https://user-images.githubusercontent.com/20582179/192635318-2053d7cb-f0b1-4d05-bc58-63d00957909b.png">

 one note i forgot to mention in our meeting—would it be possible to have the examples on white rather than a darker grey? 
![image](https://user-images.githubusercontent.com/20582179/192635465-b68b71c5-82de-4ca3-9823-f9fdf3f232c5.png)

**Comment by jdharvey-ibm** [comment]
@kingtraceyj Yeah, we can definitely do them on white!

**Comment by francinelucca** [comment]
Issue to put page in SB: #1430
