### ISSUE TITLE
Add Storybook for web app components and pages

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#320]
### Tasks

- [ ] Add Storybook in a way that works well with Next.js
- [ ] Add stories for components
- [ ] Ensure components have complete prop types
- [ ] Add stories for static pages
- [ ] Deploy Storybook somewhere (GitHub pages?)
- [ ] Add Storybook to PR as deploy previews
- [ ] https://github.com/carbon-design-system/carbon-platform/issues/319
