### ISSUE TITLE
Index libraries and assets

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#331]
### Summary

Now that the schema (shared, IBM-wide resource metadata definitions and relationships) and the catalog (single place to discover all resources from across the ecosystem) have privately launched, it's time to index libraries and assets by applying the schema to existing resources.

- [ ] Carbon Components (group)
  - [ ] Carbon Styles
  - [ ] Carbon React
  - [ ] Carbon React
  - [ ] Carbon React
  - [ ] Carbon React
- [ ] Carbon Charts (group)
  - [ ] Carbon Charts
  - [ ] Carbon Charts Angular
  - [ ] Carbon Charts React
  - [ ] Carbon Charts Svelte
  - [ ] Carbon Charts Vue
- [ ] Carbon for IBM.com
  - [ ] Carbon Styles
- [ ] Watson Moments
  - [ ] Carbon Styles

**Comment by mattrosno** [comment]
Duplicate
