### ISSUE TITLE
Web app

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#38]
- [x] #2
- [x] #245
- [x] Hook up to messaging
- [x] #232
- [x] Verify that the file caching strategy works for the Next.js build on Code Engine
- [x] Set up subdomain (next.carbondesignsystem.com)
- [x] #80 
- [x] Build a finalized container image for the beta
- [x] Deploy the finalized image to prod

**Comment by mattrosno** [comment]
@jdharvey-ibm I added this to the private beta milestone because we'll need the web app on production infrastructure. If some of the tasks go beyond what we need for the private beta, can you either remove the those tasks or move them to a different issue?

**Comment by jdharvey-ibm** [comment]
Removed the following since they are not needed for v0.1 and will be covered under other issues

> ### Optional?
>
> - [ ] Hook up to database
> - [ ] GraphQL endpoint

**Comment by mattrosno** [comment]
@jdharvey-ibm to populate remain todos like mapping subdomain to the IBM Cloud application.
