### ISSUE TITLE
WIP: Data Graph Service Epic

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#472]
**User Story**

As a UI developer, I want to query all of the data across the Platform so that I can create interesting user experiences to help people use the Carbon Design System

**Service Name:** data-graph

## API Package

- [ ] `md` create/expose a graphql tagged template literal
  ```ts
  gql`query {...}` // for example
  ```
- [ ] TODO: test infrastructure.. api package function to register queries?
- [ ] `sm` test: update express proxy to include data-graph test endpoint

## Service

- [ ] `sm` create service
- [ ] `sm` move nestjs code from PoC into service
- [ ] `md` create finalized organizational structure of code and resolvers
