### ISSUE TITLE
WIP GitHub Service Epic

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#521]
**User Stories**

As a Platform infrastructure developer, I want to be able to scale the number of indexed repos indefinitely so that I can display data from as many teams as would like to use the platform.

As a Platform UI developer, I don't want to have to maintain GitHub API logic within the UI framework so that I can focus on creating meaningful UX.

**Service Name:** github

- [ ] create a rough low-level design of how the github service talks to github (beyond what is conveyed in the SLD)

## API Package

- [ ] Determine what GitHub APIs need to be called based on the desired GraphQL queries in the data-graph service
- [ ] Create functional APIs to access all GitHub primitives
- [ ] Create message broker types for all request types

## Service
- [ ] Create NestJS application
- [ ] Create controller(s) to handle all new message types
- [ ] Create a nestjs "service" (or a couple) to interact with github's APIs via Octokit
- [ ] Add appropriate logging and ffdc
- [ ] `xl` Migrate existing API calls from web-app to the new github service
