### ISSUE TITLE
Can't index two assets that live in the same file or directory

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#74]
### Description

For example, this file has two exported functions.

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/packages/utilities/src/utilities/formatVideoCaption/formatVideoCaption.js

The docs site lists them separately.

https://ibmdotcom-utilities.mybluemix.net/global.html#formatVideoCaption

https://ibmdotcom-utilities.mybluemix.net/global.html#formatVideoDuration

Given our `carbon-library.yml` and `carbon-asset.yml` configs... we can't have two `carbon-asset.yml`s in the same duration.

Maybe we list this as a constraint where each unique asset needs to live in its own directory, and single-asset libraries need a `src` folder or something if we eventually standardize on `carbon.yml` for all configs.

### Tasks

- [x] Update `/docs/resource-schemas.md` to use `carbon.yml` files everywhere
- [x] Update docs to use the YAML language server files everywhere in that markdown file
- [x] Copy one of our test repos so we can update `carbon-library.yml` and `carbon-asset.yml` to `carbon.yml` everywhere using the `---` in the YAML files where needing to document two resources that live in the same directory
- [x] The big one, update our source code to
  - [x] Find and read contents of the `carbon.yml` files instead
  - [x] Get the catalog to work with that one updated test library (may need to clear out the test data `npm run clean:data` and then commit the changes

**Comment by mattrosno** [comment]
We can't do this because "map keys must be unique" YAML error on the second `asset:`.

carbon.yml
```yml
library:
  id: my-library
  name: My Library
asset:
  id: my-asset-1
  name: My First Asset
asset:
  id: my-asset-2
  name: My Second Asset
```

Another option, we can use the `---` to separate multiple documents in a single YAML file. See https://stackoverflow.com/a/53691066

carbon.yml
```yml
schema: library
id: my-library
name: My Library
---
schema: asset
id: my-asset-1
name: My First Asset
---
schema: asset
id: my-asset-2
name: My Second Asset
```

The question then becomes how do we validate this? Do we need the `schema:` keys? Would we be able to use one YAML language server declaration for the entire file?

carbon.yml
```yml
# yaml-language-server: $schema=https://my.url.to/the/schema

schema: library
id: my-library
name: My Library
---
schema: asset
id: my-asset-1
name: My First Asset
---
schema: asset
id: my-asset-2
name: My Second Asset
```

Or, could we do different language server declarations per document?

carbon.yml
```yml
# yaml-language-server: $schema=https://my.url.to/the/library/schema
id: my-library
name: My Library
---
# yaml-language-server: $schema=https://my.url.to/the/asset/schema
id: my-asset-1
name: My First Asset
---
# yaml-language-server: $schema=https://my.url.to/the/asset/schema
id: my-asset-2
name: My Second Asset
```

That last configuration seems ideal if the validation works on a per-document basis within the YAML file.

**Comment by mattrosno** [comment]
See 2.2 structures: https://yaml.org/spec/1.2.2

**Comment by mattrosno** [comment]
@jdharvey-ibm @francinelucca with this YAML structure:

```yml
library:
  ...all the library props
assets:
  someAssetIdentifier:
    ...all the asset props
  someSecondAssetIdentifier:
    ...all the second asset props
```

No dependency parsing schema validation files works for me. I can see how this could be structured as JSON in the future, which is nice.

I still think it's important to co-locate asset meta data in the same folder as it's source and documentation. For example, in the schema is paths to thumbnail images. In the future, paths to markdown files for usage documentation, design spec, etc. The closer the carbon.yml to the asset's source, the smaller those relative paths are. Also, by placing the carbon.yml for an asset in the same directory as its source, that means a GitHub repo can set up codeowners for that directory to assist PR review at the asset directory level.

For a data table component, if the carbon.yml is in the same folder as the data table and the library is documented in a parent directory, would the data table carbon.yml be:

```yml
assets:
  data-table:
    name: Data table
    description: ...
    externalDocsUrl: ...
```

The plural `assets` and the extra indentation doesn't seem ideal here. Is that a big deal to you or not? When the `carbon.yml` is describing only one asset?

**Comment by mattrosno** [comment]
That format works for me if it keeps the consumption logic and validation simplest on our end.
