### ISSUE TITLE
Asset catalog prototype

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#8]
### Summary

As a development-driven prototype, build a prototype for the asset catalog backed by real data from GitHub repositories.

1. Determine if the prototype should be built with Gatsby 4 or Next.js
2. Define the schema to classify libraries and assets
3. Apply schema to Carbon core (and possibly PAL) libraries through forked/branched GitHub repositories
4. Fetch that data to populate the various **asset catalogs, catalog filtering, and entries in each catalog**

### Job stories

- [x] https://github.com/carbon-design-system/carbon-job-stories/issues/24
- [x] https://github.com/carbon-design-system/carbon-job-stories/issues/28
- [x] https://github.com/carbon-design-system/carbon-job-stories/issues/31
- [x] https://github.com/carbon-design-system/carbon-job-stories/issues/23
- [ ] https://github.com/carbon-design-system/carbon-job-stories/issues/27
- [ ] https://github.com/carbon-design-system/carbon-job-stories/issues/29
- [ ] https://github.com/carbon-design-system/carbon-job-stories/issues/30
- [ ] https://github.com/carbon-design-system/carbon-job-stories/issues/32
- [ ] https://github.com/carbon-design-system/carbon-job-stories/issues/49

### Success measures

- Decisions made: React framework
- Concepts proven: remote, versioned, GitHub content
- Outstanding issues and questions identified to address in a follow-up sprint

### Definition of done

The follow items don't need to be "done done" in the prototype to hit the success metrics:

- Browsers and devices other than Chrome
- Accessibility (screen readers, keyboard navigation, etc.)
- Design pixel precision, especially when the underlying issue is with a Carbon component and outside the scope of the platform squad to fix

### Tasks

- [x] #10
- [x] #11
- [x] #24
- [x] #30
- [x] #34
- [x] #28
- [x] #12
- [x] #31
- [x] #33
- [x] #135
- [x] #32
- [x] #16 
- [x] #29
